model:
  name: unet3d
  type: cnn

framework: pytorch

train:
  communication: False
  compute: True
  computation_time:
    shape: 55.8006
    scale: 0.0129793
    type: gamma

workflow:
 generate_data: False
 train: True

dataset:
  num_files_train: 168
  num_samples_per_file: 1
  record_length_bytes: 146600628
  data_folder: data/unet3d/
  format: npz


reader:
 data_loader: pytorch
 read_threads: 4
 computation_threads: 1
 batch_size: 7

